global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flight-service'
    static_configs:
      - targets: ['host.docker.internal:5001']

  - job_name: 'booking-service'
    static_configs:
      - targets: ['host.docker.internal:5002']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:5003']
