pipeline {
    agent any

    environment {
        SERVICE_NAME = "payment-service"
        IMAGE_NAME = "payment-service-img"
        CONTAINER_NAME = "payment-test"
        PORT = "5003"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                dir("${env.SERVICE_NAME}") {
                    sh "docker build -t ${env.IMAGE_NAME} ."
                }
            }
        }

        stage('Run Container') {
            steps {
                sh "docker stop ${env.CONTAINER_NAME} || true"
                sh "docker rm ${env.CONTAINER_NAME} || true"
                sh "docker run -d -p ${env.PORT}:${env.PORT} --name ${env.CONTAINER_NAME} ${env.IMAGE_NAME}"
            }
        }

        stage('Cleanup') {
            steps {
                sh "docker stop ${env.CONTAINER_NAME}"
                sh "docker rm ${env.CONTAINER_NAME}"
            }
        }
    }
}
