pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("payment-service-img")
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    docker.image("payment-service-img").run("-p 5003:5003")
                }
            }
        }
    }
}
