pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("booking-service-img")
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    docker.image("booking-service-img").run("-p 5002:5002")
                }
            }
        }
    }
}
